### PR TITLE
Users can now update profile

### PR DESCRIPTION
**Pull request by lucydisalvo**
Added updateProfile() function to accountController, update_profile.php in ~/views/account 

>Users can change their name, last name and email

### CODE REVIEW

**Review by MikeLup — APPROVED** [review]

**Comment by bferrari0617** [comment]
The pathing seems to be incorrect - clicking profile on the dropdown brings me to an error page and not the actual profile page.

**Comment by lucydisalvo** [comment]
I'll check it out





Lucy DiSalvo '25

BS Computer Science | ***@***.***

College of Engineering and Computer Science



Syracuse University




________________________________

**Comment by bferrari0617** [comment]
I fixed it.

**Comment by lucydisalvo** [comment]
Ok awesome, and the profile is showing + you can update your information?

**Pull request merged**
